# Generated by Django 3.1.5 on 2021-02-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_sale_amountreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pendingMedicalCharge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
