# Generated by Django 3.1.5 on 2021-02-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patient_pendingmedicalcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='itemName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
