# Generated by Django 3.1.5 on 2021-02-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_sale_itemname'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.IntegerField(default=0, null=True)),
                ('patientName', models.CharField(blank=True, max_length=50, null=True)),
                ('testName', models.CharField(choices=[('Complete Blood Count', 'Complete Blood Count'), ('Prothrombin Time', 'Prothrombin Time'), ('Basic Metabolic Panel', 'Basic Metabolic Panel'), ('Comprehensive Metabolic Panel', 'Comprehensive Metabolic Panel'), ('Lipid Panel', 'Lipid Panel'), ('Liver Panel', 'Liver Panel'), ('Thyroid Stimulating Hormone', 'Thyroid Stimulating Hormone'), ('Hemoglobin A1C', 'Hemoglobin A1C'), ('Urinalysis', 'Urinalysis'), ('Cultures', 'Cultures')], default='Complete Blood Count', max_length=128)),
                ('testResult', models.TextField(max_length=750)),
                ('paymentStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
