# Generated by Django 3.1.5 on 2021-02-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210218_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='testName',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
