# Generated by Django 3.1.5 on 2021-02-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20210218_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pendingLabTestCharge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
