# Generated by Django 3.1.5 on 2021-02-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_patient_pendinglabtestcharge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDischargeDetail',
            new_name='PatientDischargeDetails',
        ),
    ]
