# Generated by Django 3.1.5 on 2021-02-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20210218_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='labTestCost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='OtherCharge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='daySpent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='doctorFee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='medicineCost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='roomCharge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
