# Generated by Django 3.1.5 on 2021-02-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20210218_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='testDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='saleDate',
            field=models.DateField(auto_now=True),
        ),
    ]
